-- lua starts from root directory
local lib = require("Lua.20210915Review.lib")
lib.var_demo()
lib.func_demo()
lib.statement_demo()
lib.controlflow_demo()
lib.loop_demo()
lib.mt_demo()
lib.fileio_demo()
lib.oop_demo()
lib.coroutine_demo()