/*

JS meta-language review

[JS meta]
----

----

*/ 

function VariableDmo() {
    /*
    
    [Variables]
    ----
    * declaration and definition
        ** pattern: T N V
        ** default value? "undefined"

    * keywords
        ** var
        ** let
        ** const

    * data types
        ** Undefined
        ** Null
        ** String
        ** Number
        ** Integer
        ** Decimal
    
    * type conversion
        ** Boolean()
        ** Number()
        ** String()

        ** Number.parseFloat()
        ** Number.parseInt()

    * reflection
        ** IsNaN()
        ** Typeof
    ----
    
    */ 
    
}

function Main() {
    
    // variable
    VariableDmo()
    // funtion
    
    // statement
    
    // control flow
    
    // loop
    
    // class
    
    // container
    
    // DOM
    
    // import

}